name: 'linux_10_10-win'

on: push

jobs:
  build:
    runs-on: 'ubuntu-20.04'

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v1
      with:
        node-version: '10.0.0'

    - run: npm install
    - run: npm run clean
    - run: npm run shockpkg -- update --summary
    - run: npm run shockpkg -- install shockwave-projector-director-10.0.0-mac-win shockwave-projector-director-10.0.0-win-win shockwave-projector-director-10.1.0-mac-win shockwave-projector-director-10.1.0-win-win shockwave-projector-director-10.1.1-mac-win shockwave-projector-director-10.1.1-win-win

    - run: npm run build
    - run: npm run test
