name: 'linux_16_11.5-win'

on: push

jobs:
  build:
    runs-on: 'ubuntu-20.04'

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v1
      with:
        node-version: '16.5.0'

    - run: npm install
    - run: npm run clean
    - run: npm run shockpkg -- update --summary
    - run: npm run shockpkg -- install shockwave-projector-director-11.5.0-mac-win shockwave-projector-director-11.5.0-win-win shockwave-projector-director-11.5.8-mac-win shockwave-projector-director-11.5.8-win-win shockwave-projector-director-11.5.9-mac-win shockwave-projector-director-11.5.9-win-win

    - run: npm run build
    - run: npm run test
