name: 'linux_16_11.0-win'

on: push

jobs:
  build:
    runs-on: 'ubuntu-20.04'

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v1
      with:
        node-version: '16.1.0'

    - run: npm install
    - run: npm run clean
    - run: npm run shockpkg -- update --summary
    - run: npm run shockpkg -- install shockwave-projector-director-11.0.0-mac-win shockwave-projector-director-11.0.0-win-win shockwave-projector-director-11.0.0-hotfix-1-mac-win shockwave-projector-director-11.0.0-hotfix-3-mac-win shockwave-projector-director-11.0.0-hotfix-3-win-win

    - run: npm run build
    - run: npm run test
