name: main

on: push

jobs:
  build:
    strategy:
      matrix:
        config:
          - node-version: '14.15.0' # LTS
            NO_FORMATTED: 1
            NO_LINT: 1
            PKGSET: ''
            PKG: ''

          - node-version: '16.13.0' # LTS
            NO_FORMATTED: 1
            NO_LINT: 1
            PKGSET: ''
            PKG: ''

          - node-version: '18.12.0' # LTS (current)
            PKGSET: ''
            PKG: ''

          - node-version: '19.0.0' # Latest
            PKGSET: ''
            PKG: ''

          - node-version: '18.12.0' # LTS (current)
            NO_FORMATTED: 1
            NO_LINT: 1
            PKGSET: '7-windows'
            PKG:
              - shockwave-projector-director-7.0.0-win-win
              - shockwave-projector-director-7.0.2-2-win-win
              - shockwave-projector-director-7.0.2-trial-win-win
              - shockwave-projector-director-7.0.2-win-win

          - node-version: '18.12.0' # LTS (current)
            NO_FORMATTED: 1
            NO_LINT: 1
            PKGSET: '8-windows'
            PKG:
              - shockwave-projector-director-8.0.0-trial-win-win
              - shockwave-projector-director-8.0.0-win-win

          - node-version: '18.12.0' # LTS (current)
            NO_FORMATTED: 1
            NO_LINT: 1
            PKGSET: '8.5-windows'
            PKG:
              - shockwave-projector-director-8.5.0-win-win
              - shockwave-projector-director-8.5.0-trial-win-win
              - shockwave-projector-director-8.5.1-win-win
              - shockwave-projector-director-8.5.1-trial-win-win

          - node-version: '18.12.0' # LTS (current)
            NO_FORMATTED: 1
            NO_LINT: 1
            PKGSET: '9-windows'
            PKG:
              - shockwave-projector-director-9.0.0-win-win
              - shockwave-projector-director-9.0.0-trial-win-win

          - node-version: '18.12.0' # LTS (current)
            NO_FORMATTED: 1
            NO_LINT: 1
            PKGSET: '10-windows'
            PKG:
              - shockwave-projector-director-10.0.0-mac-win
              - shockwave-projector-director-10.0.0-win-win
              - shockwave-projector-director-10.1.0-mac-win
              - shockwave-projector-director-10.1.0-win-win
              - shockwave-projector-director-10.1.1-mac-win
              - shockwave-projector-director-10.1.1-win-win

          - node-version: '18.12.0' # LTS (current)
            NO_FORMATTED: 1
            NO_LINT: 1
            PKGSET: '11-windows'
            PKG:
              - shockwave-projector-director-11.0.0-mac-win
              - shockwave-projector-director-11.0.0-win-win
              - shockwave-projector-director-11.0.0-hotfix-1-mac-win
              - shockwave-projector-director-11.0.0-hotfix-3-mac-win
              - shockwave-projector-director-11.0.0-hotfix-3-win-win

          - node-version: '18.12.0' # LTS (current)
            NO_FORMATTED: 1
            NO_LINT: 1
            PKGSET: '11.5-windows'
            PKG:
              - shockwave-projector-director-11.5.0-mac-win
              - shockwave-projector-director-11.5.0-win-win
              - shockwave-projector-director-11.5.8-mac-win
              - shockwave-projector-director-11.5.8-win-win
              - shockwave-projector-director-11.5.9-mac-win
              - shockwave-projector-director-11.5.9-win-win

          - node-version: '18.12.0' # LTS (current)
            NO_FORMATTED: 1
            NO_LINT: 1
            PKGSET: '12-windows'
            PKG:
              - shockwave-projector-director-12.0.0-mac-win
              - shockwave-projector-director-12.0.0-win-win
              - shockwave-projector-director-12.0.2-mac-win
              - shockwave-projector-director-12.0.2-win-win

          - node-version: '18.12.0' # LTS (current)
            NO_FORMATTED: 1
            NO_LINT: 1
            PKGSET: '11-mac'
            PKG:
              - shockwave-projector-director-11.0.0-mac-mac-zip
              - shockwave-projector-director-11.0.0-win-mac-zip
              - shockwave-projector-director-11.0.0-hotfix-1-mac-mac-zip
              - shockwave-projector-director-11.0.0-hotfix-3-mac-mac-zip
              - shockwave-projector-director-11.0.0-hotfix-3-win-mac-zip

          - node-version: '18.12.0' # LTS (current)
            NO_FORMATTED: 1
            NO_LINT: 1
            PKGSET: '11.5-mac'
            PKG:
              - shockwave-projector-director-11.5.0-mac-mac-zip
              - shockwave-projector-director-11.5.0-win-mac-zip
              - shockwave-projector-director-11.5.8-mac-mac-zip
              - shockwave-projector-director-11.5.8-win-mac-zip
              - shockwave-projector-director-11.5.9-mac-mac-zip
              - shockwave-projector-director-11.5.9-win-mac-zip

          - node-version: '18.12.0' # LTS (current)
            NO_FORMATTED: 1
            NO_LINT: 1
            PKGSET: '12-mac'
            PKG:
              - shockwave-projector-director-12.0.0-mac-mac-zip
              - shockwave-projector-director-12.0.0-win-mac-zip
              - shockwave-projector-director-12.0.2-mac-mac-zip
              - shockwave-projector-director-12.0.2-win-mac-zip

    runs-on: 'ubuntu-20.04'

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.config.node-version }}

      - name: Dependencies
        run: npm ci

      - name: shockpkg Cache
        uses: actions/cache@v3
        if: matrix.config.PKGSET != 1
        with:
          key: shockpkg-${{ matrix.config.pkgset }}
          path: shockpkg

      - name: shockpkg Update
        run: npm run shockpkg -- update --summary

      - name: shockpkg Install
        run: npm run shockpkg -- install ${{ join(matrix.config.PKG, ' ') }}
        if: matrix.config.PKG != ''

      - name: Build
        run: npm run build

      - name: Test CJS
        run: npm run test:cjs

      - name: Test ESM
        run: npm run test:esm

      - name: Lint
        run: npm run lint
        if: matrix.config.NO_LINT != 1

      - name: Formatted
        run: npm run formatted
        if: matrix.config.NO_FORMATTED != 1

  publish:
    if: startsWith(github.ref, 'refs/tags/')
    needs: build

    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Node
        uses: actions/setup-node@v3
        with:
          node-version: '18.12.0'
          registry-url: https://registry.npmjs.org/

      - name: Dependencies
        run: npm ci

      - name: Publish
        run: npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
